services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python myapp.py"
    envVars:
      - key: PORT
        value: 5000
